import geopandas as gpd
import shapely as sp
from matplotlib import pyplot as plt


line_a = sp.LineString([(0, 0), (2, 2)])
line_b = sp.LineString([(2,2), (2, 0)])

poly1=sp.Polygon([(0, 0), (2, 0), (2, 2), (0, 2)])
poly2=sp.Polygon([(1, 1), (3, 1), (3, 3), (1, 3)])


point1=sp.Point((2, 0))
point2=sp.Point(2, 1)
print("PAIRES DE LIGNES")
inters=line_a.intersects(line_a)
print(inters)
withi=line_a.within(line_b)
print(withi)
cont=line_a.contains(line_b)
print(cont)
over=line_a.overlaps(line_b)
print(over)
touch=line_a.touches(line_b)
print(touch)
cov=line_a.covers(line_b)
print(cov)
coverby=line_a.covered_by(line_b)
print(coverby)
eq=line_a.equals(line_b)
print(eq)
disj=line_a.disjoint(line_b)
print(disj)
cros=line_a.crosses(line_b)
print(cros)

print("PAIRES DE POLYGONE")
inters=poly1.intersects(poly2)
print(inters)
withi=poly1.within(poly2)
print(withi)
cont=poly1.contains(poly2)
print(cont)
over=poly1.overlaps(poly2)
print(over)
touch=poly1.touches(poly2)
print(touch)
cov=poly1.covers(poly2)
print(cov)
coverby=poly1.covered_by(poly2)
print(coverby)
eq=poly1.equals(poly2)
print(eq)
disj=poly1.disjoint(poly2)
print(disj)
cros=poly1.crosses(poly2)
print(cros)
print("PAIRES DE POINT")
inters=poly1.intersects(poly2)
print(inters)
withi=poly1.within(poly2)
print(withi)
cont=poly1.contains(poly2)
print(cont)
over=poly1.overlaps(poly2)
print(over)
touch=poly1.touches(poly2)
print(touch)
cov=poly1.covers(poly2)
print(cov)
coverby=poly1.covered_by(poly2)
print(coverby)
eq=poly1.equals(poly2)
print(eq)
disj=poly1.disjoint(poly2)
print(disj)
cros=poly1.crosses(poly2)
print(cros)
gdf=gpd.GeoDataFrame(geometry=[poly1,poly2])
gdf.plot()
plt.show()